version: 2.1
orbs:
  dr-data-sonarcloud: dealroom/data-sonarcloud@0.0.4

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  service:
    type: string
    default: ""

workflows:
  test-build-push-deploy:
    jobs:
      - dr-data-sonarcloud/test-and-scan-single-project-repo:
          context: data-sonarcloud
          python_version: '3.8'


