version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  setup-and-test:
    parameters:
      tests_dir:
        type: string
      source_dir:
        type: string
        default: .
    executor: python/default
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd << parameters.source_dir >>
            pip3 install -r requirements-dev.txt
      - run:
          name: Run tests
          command: |
            mkdir test-results
            python3 -m pytest --junitxml=<< parameters.source_dir >>/test-results/junit.xml << parameters.source_dir >>/<< parameters.tests_dir >>
      - store_test_results:
          path: << parameters.source_dir >>/test-results

workflows:
  test:
    jobs:
      - setup-and-test:
          tests_dir: "tests"
