version: 2.1
orbs:
  dr-data-sonarcloud: dealroom/data-sonarcloud@0.0.2

workflows:
  run-tests-and-scan:
    jobs:
      - dr-data-sonarcloud/test-and-scan-single-project-repo:
          context: data-sonarcloud
          xml_coverage_report: coverage.xml
          debug: true
